<?php
/**
 * Theqqa - Classified Ads Web Application
 * Copyright (c) BedigitCom. All Rights Reserved
 *
 * Website: http://www.
 *
 * Theqqa
 */

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\City;
use Illuminate\Support\Facades\Cache;
use Torann\LaravelMetaTags\Facades\MetaTag;


/**
 * Class ApiController
 *
 * @package App\Http\Controllers
 *
 * @SWG\Swagger(
 *     basePath="",
 *     host="127.0.0.1:8000",
 *     schemes={"http"},
 *     @SWG\Info(
 *         version="1.0",
 *         title="theqqa API",
 *         @SWG\Contact(name="Pek Ratanak", url="http://127.0.0.1:8000"),
 *     ),
 *     @SWG\SecurityScheme(
 *     securityDefinition="default",
 *          type="apiKey",
 *          in="header",
 *          name="Authorization"),
 *     @SWG\Definition(
 *         definition="Error",
 *         required={"code", "message"},
 *         @SWG\Property(
 *             property="code",
 *             type="integer",
 *             format="int32"
 *         ),
 *         @SWG\Property(
 *             property="message",
 *             type="string"
 *         )
 *     )

 * )
 */
class ApiController   extends FrontController
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    /**
     * @SWG\Post(
     *     path="/api/login",
     *     description="Return a user's first and last name",

     *     @SWG\Parameter(
     *         name="login",
     *         in="formData",
     *         type="string",
     *         description="login",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="password",
     *         in="formData",
     *         type="string",
     *         description="password",
     *         required=true,
     *     ),
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *
     *
     *
     *
     *
     *   @SWG\Post(
     *     path="/api/register",
     *     description="Return a user's first and last name",

     *     @SWG\Parameter(
     *         name="name",
     *         in="formData",
     *         type="string",
     *         description="name",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="email",
     *         in="formData",
     *         type="string",
     *         description="email",
     *         required=true,
     *     ),
     *         @SWG\Parameter(
     *         name="password",
     *         in="formData",
     *         type="string",
     *         description="password",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="password_confirmation",
     *         in="formData",
     *         type="string",
     *         description="password_confirmation",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="term",
     *         in="formData",
     *         type="string",
     *         description="term",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="id_number",
     *         in="formData",
     *         type="string",
     *         description="id_number",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="phone",
     *         in="formData",
     *         type="string",
     *         description="phone",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="id_number_owner",
     *         in="formData",
     *         type="string",
     *         description="id_number_owner",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="subladmin1",
     *         in="formData",
     *         type="string",
     *         description="subladmin1",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *      description="file",
     *      in="formData",
     *      name="file",
     *      required=true,
     *       type="file",
     *     ),
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Post(
     *     path="/api/contactfor/mogaz",
     *     description="mogaz no & yes ",
     *      security={{"default":{}}},

     *     @SWG\Parameter(
     *         name="bank_transfer_in",
     *         in="formData",
     *         type="file",
     *         description="bank_transfer_in",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="email",
     *         in="formData",
     *         type="string",
     *         description="email",
     *         required=true,
     *     ),
     *         @SWG\Parameter(
     *         name="first_name",
     *         in="formData",
     *         type="string",
     *         description="first_name",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="service_type",
     *         in="formData",
     *         type="string",
     *         description="service_type",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="owner_id",
     *         in="formData",
     *         type="string",
     *         description="owner_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="plate_number",
     *         in="formData",
     *         type="string",
     *         description="plate_number",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="serial_number",
     *         in="formData",
     *         type="string",
     *         description="serial_number",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="package_id",
     *         in="formData",
     *         type="string",
     *         description="package_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="payment_method_id",
     *         in="formData",
     *         type="string",
     *         description="payment_method_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *      description="for_mogaz",
     *      in="formData",
     *      name="for_mogaz",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="car_url",
     *      in="formData",
     *      name="car_url",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Post(
     *     path="/api/contactfor/shipping",
     *     description="shipping no & yes ",
     *      security={{"default":{}}},
     *     @SWG\Parameter(
     *         name="service_type",
     *         in="formData",
     *         type="string",
     *         description="service_type",
     *         required=true,
     *     ),
     *       @SWG\Parameter(
     *         name="first_name",
     *         in="formData",
     *         type="string",
     *         description="first_name",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="email",
     *         in="formData",
     *         type="string",
     *         description="email",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *      description="car_url",
     *      in="formData",
     *      name="car_url",
     *      required=true,
     *       type="string",
     *     ),
     *      @SWG\Parameter(
     *         name="shipping_place",
     *         in="formData",
     *         type="string",
     *         description="shipping_place",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="shipping_id",
     *         in="formData",
     *         type="string",
     *         description="shipping_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="address",
     *         in="formData",
     *         type="string",
     *         description="address",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="owner_id",
     *         in="formData",
     *         type="string",
     *         description="owner_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="plate_number",
     *         in="formData",
     *         type="string",
     *         description="plate_number",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="serial_number",
     *         in="formData",
     *         type="string",
     *         description="serial_number",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="bank_transfer_in",
     *         in="formData",
     *         type="file",
     *         description="bank_transfer_in",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *      description="shipping_place_to",
     *      in="formData",
     *      name="shipping_place_to",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="address_to",
     *      in="formData",
     *      name="address_to",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="car_Pictures",
     *      in="formData",
     *      name="car_Pictures",
     *      required=true,
     *       type="file",
     *     ),
     *     @SWG\Parameter(
     *      description="for_shipping",
     *      in="formData",
     *      name="for_shipping",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *         name="package_id",
     *         in="formData",
     *         type="string",
     *         description="package_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="payment_method_id",
     *         in="formData",
     *         type="string",
     *         description="payment_method_id",
     *         required=true,
     *     ),
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Post(
     *     path="/api/contactfor/ownership",
     *     description="ownership no & yes ",
     *     security={{"default":{}}},
     *     @SWG\Parameter(
     *         name="service_type",
     *         in="formData",
     *         type="string",
     *         description="service_type",
     *         required=true,
     *     ),
     *       @SWG\Parameter(
     *         name="first_name",
     *         in="formData",
     *         type="string",
     *         description="first_name",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="email",
     *         in="formData",
     *         type="string",
     *         description="email",
     *         required=true,
     *     ),

     *      @SWG\Parameter(
     *         name="purchaser_name",
     *         in="formData",
     *         type="string",
     *         description="purchaser_name",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="owner_id",
     *         in="formData",
     *         type="string",
     *         description="owner_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="user_id",
     *         in="formData",
     *         type="string",
     *         description="user_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="seller_phone",
     *         in="formData",
     *         type="string",
     *         description="seller_phone",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="purchaser_phone",
     *         in="formData",
     *         type="string",
     *         description="purchaser_phone",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="Kilometers",
     *         in="formData",
     *         type="string",
     *         description="Kilometers",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="price",
     *         in="formData",
     *         type="string",
     *         description="price",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *      description="driving_license",
     *      in="formData",
     *      name="driving_license",
     *      required=true,
     *       type="file",
     *     ),
     *     @SWG\Parameter(
     *      description="purchaser_id_image",
     *      in="formData",
     *      name="purchaser_id_image",
     *      required=true,
     *       type="file",
     *     ),
     *     @SWG\Parameter(
     *      description="exhibitions_place",
     *      in="formData",
     *      name="exhibitions_place",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="exhibitions_id",
     *      in="formData",
     *      name="exhibitions_id",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *         name="for_ownership",
     *         in="formData",
     *         type="string",
     *         description="for_ownership",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="car_url",
     *         in="formData",
     *         type="string",
     *         description="car_url",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="seller_name",
     *         in="formData",
     *         type="string",
     *         description="seller_name",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="seller_id_image",
     *         in="formData",
     *         type="file",
     *         description="seller_id_image",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="car_Pictures",
     *         in="formData",
     *         type="file",
     *         description="car_Pictures",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="package_id",
     *         in="formData",
     *         type="string",
     *         description="package_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="payment_method_id",
     *         in="formData",
     *         type="string",
     *         description="payment_method_id",
     *         required=true,
     *     ),
     *      @SWG\Parameter(
     *         name="bank_transfer_in",
     *         in="formData",
     *         type="file",
     *         description="bank_transfer_in",
     *         required=true,
     *     ),
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *
     *
     *
     *
     *   @SWG\Post(
     *     path="/api/contactfor/maintenance",
     *     description="maintenance no & yes ",
     *    security={{"default":{}}},
     *     @SWG\Parameter(
     *         name="service_type",
     *         in="formData",
     *         type="string",
     *         description="service_type",
     *         required=true,
     *     ),
     *       @SWG\Parameter(
     *         name="first_name",
     *         in="formData",
     *         type="string",
     *         description="first_name",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="email",
     *         in="formData",
     *         type="string",
     *         description="email",
     *         required=true,
     *     ),

     *      @SWG\Parameter(
     *         name="car_url",
     *         in="formData",
     *         type="string",
     *         description="car_url",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="package_id",
     *         in="formData",
     *         type="string",
     *         description="package_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="payment_method_id",
     *         in="formData",
     *         type="string",
     *         description="payment_method_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="bank_transfer_in",
     *         in="formData",
     *         type="file",
     *         description="bank_transfer_in",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="shipping_id",
     *         in="formData",
     *         type="string",
     *         description="shipping_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="address",
     *         in="formData",
     *         type="string",
     *         description="address",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="owner_id",
     *         in="formData",
     *         type="string",
     *         description="owner_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *      description="plate_number",
     *      in="formData",
     *      name="plate_number",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="car_place",
     *      in="formData",
     *      name="car_place",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="maintenance_id",
     *      in="formData",
     *      name="maintenance_id",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="maintenance_id_yes",
     *      in="formData",
     *      name="maintenance_id_yes",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *         name="for_mainten",
     *         in="formData",
     *         type="string",
     *         description="for_mainten",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="car_url",
     *         in="formData",
     *         type="string",
     *         description="car_url",
     *         required=true,
     *     ),

     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Post(
     *     path="/api/contactfor/checking",
     *     description="checking",
     *   security={{"default":{}}},
     *     @SWG\Parameter(
     *         name="service_type",
     *         in="formData",
     *         type="string",
     *         description="service_type",
     *         required=true,
     *     ),
     *       @SWG\Parameter(
     *         name="first_name",
     *         in="formData",
     *         type="string",
     *         description="first_name",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="email",
     *         in="formData",
     *         type="string",
     *         description="email",
     *         required=true,
     *     ),

     *      @SWG\Parameter(
     *         name="car_url",
     *         in="formData",
     *         type="string",
     *         description="car_url",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="package_id",
     *         in="formData",
     *         type="string",
     *         description="package_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="payment_method_id",
     *         in="formData",
     *         type="string",
     *         description="payment_method_id",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="bank_transfer_in",
     *         in="formData",
     *         type="file",
     *         description="bank_transfer_in",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="checking_time",
     *         in="formData",
     *         type="string",
     *         description="checking_time",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="address",
     *         in="formData",
     *         type="string",
     *         description="address",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *         name="phone",
     *         in="formData",
     *         type="string",
     *         description="phone",
     *         required=true,
     *     ),
     *     @SWG\Parameter(
     *      description="checking_date",
     *      in="formData",
     *      name="checking_date",
     *      required=true,
     *       type="string",
     *     ),


     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Get(
     *     path="/api/contactfor/checking",
     *     description="checking",
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Get(
     *     path="/api/contactfor/mogaz",
     *     description="mogaz",
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Get(
     *     path="/api/contactfor/maintenance",
     *     description="maintenance",
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Get(
     *     path="/api/contactfor/shipping",
     *     description="shipping",
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Get(
     *     path="/api/contactfor/ownership",
     *     description="ownership",
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Get(
     *     path="/api/home/getSponsoredPosts",
     *     description="getSponsoredPosts",
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *   @SWG\Get(
     *     path="/api/home/getLatestPosts",
     *     description="getLatestPosts",
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     *      @SWG\Post(
     *     path="/api/posts/create",
     *     description="Greate Posts",
     *   security={{"default":{}}},
     *        @SWG\Parameter(
     *      description="category_id",
     *      in="formData",
     *      name="category_id",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="title",
     *      in="formData",
     *      name="title",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="description",
     *      in="formData",
     *      name="description",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="contact_name",
     *      in="formData",
     *      name="contact_name",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="email",
     *      in="formData",
     *      name="email",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="phone",
     *      in="formData",
     *      name="phone",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="city_id",
     *      in="formData",
     *      name="city_id",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="parent_id",
     *      in="formData",
     *      name="parent_id",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="package_id",
     *      in="formData",
     *      name="package_id",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="payment_method_id",
     *      in="formData",
     *      name="payment_method_id",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="active",
     *      in="formData",
     *      name="active",
     *      required=true,
     *       type="string",
     *     ),

     *     @SWG\Parameter(
     *      description="pictures",
     *      in="formData",
     *      name="pictures",
     *      required=true,
     *       type="file",
     *     ),
     *     @SWG\Parameter(
     *      description="post_type_id",
     *      in="formData",
     *      name="post_type_id",
     *      required=true,
     *       type="string",
     *     ),
     *         @SWG\Parameter(
     *      description="price",
     *      in="formData",
     *      name="price",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="tags",
     *      in="formData",
     *      name="tags",
     *      required=true,
     *       type="string",
     *     ),
     *     @SWG\Parameter(
     *      description="bank_transfer_in",
     *      in="formData",
     *      name="bank_transfer_in",
     *      required=true,
     *       type="file",
     *     ),
     *     @SWG\Response(
     *         response=200,
     *         description="OK",
     *     ),
     *     @SWG\Response(
     *         response=422,
     *         description="Missing Data"
     *     )
     * )
     */

}
